"""is core added

Revision ID: 78dcc1313530
Revises: b6beeecb606e
Create Date: 2023-10-11 19:49:47.055818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78dcc1313530'
down_revision = 'b6beeecb606e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_core', sa.Boolean(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('date_joined')
        batch_op.drop_column('date_left_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_left_on', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_joined', sa.DATETIME(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_core')

    # ### end Alembic commands ###
