"""some changes

Revision ID: 9bcd6225f157
Revises: d69a870d9d28
Create Date: 2023-10-15 21:44:40.695415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcd6225f157'
down_revision = 'd69a870d9d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('drive_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=255), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('partner_link')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('linkedin_link')
        batch_op.drop_column('instagram_link')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('date')
        batch_op.drop_column('mode')
        batch_op.drop_column('venue')
        batch_op.drop_column('drive_link')
        batch_op.drop_column('pdf_link')
        batch_op.drop_column('linkedin_link')
        batch_op.drop_column('instagram_link')

    # ### end Alembic commands ###
