"""Project model Created

Revision ID: b6beeecb606e
Revises: 23328f7581f9
Create Date: 2023-10-10 20:17:22.405254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6beeecb606e'
down_revision = '23328f7581f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partner', sa.String(length=255), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('pdf_link', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('instagram_link', sa.String(length=255), nullable=True),
    sa.Column('linkedin_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
